### ISSUE TITLE
ARM version is not working on a a1 max 

### ISSUE THREAD

**Issue by avi-stx** [VasylBaran/CommandShift#1]
ARM version is not working on a a1 max

**Comment by VasylBaran** [comment]
> ARM version is not working on a a1 max

Could you explain in more detail? Are you getting some error message? And could also mention your MacOS version? Thanks

**Comment by unickq** [comment]
<img width="248" alt="image" src="https://user-images.githubusercontent.com/6696821/152587752-a61d88a7-98c1-4da5-b568-e1b6070e71be.png">

<img width="505" alt="image" src="https://user-images.githubusercontent.com/6696821/152587767-01e5e112-e071-4540-adc5-52f0fccb62e4.png">

**Comment by VasylBaran** [comment]
> m1 pro
> 
> <img alt="image" width="248" src="https://user-images.githubusercontent.com/6696821/152587752-a61d88a7-98c1-4da5-b568-e1b6070e71be.png">
> 
> <img alt="image" width="451" src="https://user-images.githubusercontent.com/6696821/152587840-3d48ce45-85b6-4d76-aabb-abcb148c91cc.png">

Ah, that's probably because I used Big Sur to compile the app. I'll get a copy of Monterey and re-compile CommandShift in the coming days. Thanks for reporting the issue, btw! ;-)

**Comment by VasylBaran** [comment]
**UPDATE:** I've just upgraded to Monterey and the current version of CommandShift still runs fine. After googling the issue I've reasized that it's most likely due to Security settings. The following solution should help:

> Navigate to System Preferences, select Security and Privacy, and go to General. Go to Allow apps downloaded from and select Anywhere. In other words, you’re allowing non-App Store apps to run on your machine.

Please let me know if it helped. Cheers! ;-)

**Comment by unickq** [comment]
@VasylBaran 

<img width="337" alt="image" src="https://user-images.githubusercontent.com/6696821/152692166-6012ef85-68cc-4ad7-a610-f52638711414.png">

`sudo spctl --master-disable` allows it, but doesn't help much

<img width="583" alt="image" src="https://user-images.githubusercontent.com/6696821/152692297-ea8a04f3-85d8-460c-ad21-bbdbd7596183.png">

**Comment by VasylBaran** [comment]
hmm.. try downloading it again (now I've also uploaded releases to this GitHub repository: https://github.com/VasylBaran/CommandShift/tree/main/Releases)

And after downloading please verify checksums, they should match with the ones mentioned in the **"Latest installer checksums (MD5)"** section here: https://github.com/VasylBaran/CommandShift/blob/main/README.md

To check MD5 checksum of your local dmg-file you can use this command: 
`md5 Intel_CommandShift-Installer.dmg`
or 
`md5 ARM64_CommandShift-Installer.dmg`

**Comment by BEGEMOT9I** [comment]
@VasylBaran Hi! I've tried current version on M1 Pro and it still not working by the same reason (warning about damaged app) :(

**Comment by anorudes** [comment]
Yep, it's not working on m1 :'(

**Comment by VasylBaran** [comment]
@BEGEMOT9I @anorudes @avirosenberg @unickq I just re-uploaded a new ARM64 version. Could you please give it another try and let me know the result? Something weird was happening but I really hope I got it fixed this time =)

**Comment by BEGEMOT9I** [comment]
@VasylBaran Hi again! I tried your solution, it works, the application starts normally, but changing the language by pressing any of the combinations, that are in the list, still does not work. If you want, you can write to me in TG (@BEGEMOT9I) and try to debug together)

**Comment by VasylBaran** [comment]
> @VasylBaran Hi again! I tried your solution, it works, the application starts normally, but changing the language by pressing any of the combinations, that are in the list, still does not work. If you want, you can write to me in TG (@BEGEMOT9I) and try to debug together)

ok, and did you add CommandShift to "Security & Privacy -> Privacy -> Accessibility" ?

**Comment by BEGEMOT9I** [comment]
Yeah)

**Comment by VasylBaran** [comment]
<img width="663" alt="Screenshot 2022-02-20 at 14 06 36" src="https://user-images.githubusercontent.com/12252940/154841615-a6b19cba-7e45-480d-9733-7a2ebc4abce1.png">
@BEGEMOT9I ok, and the last question: do you have system level "language shorts" set to default like on this screenshot? :

**Comment by BEGEMOT9I** [comment]
Not exactly, for "previous input source" i have cmd + space

**Comment by BEGEMOT9I** [comment]
Ooo, i've got it) Yeah, with default ctrl+space this app is working well 👍 
I think it must be described in README in order to avoid misunderstanding

**Comment by VasylBaran** [comment]
> Ooo, i've got it) Yeah, with default ctrl+space this app is working well 👍 I think it must be described in README in order to avoid misunderstanding

I'm glad it worked for you. Yes, you're right - I'll update the README. Thanks again! ;-)

**Comment by BEGEMOT9I** [comment]
> > Ooo, i've got it) Yeah, with default ctrl+space this app is working well 👍 I think it must be described in README in order to avoid misunderstanding
> 
> I'm glad it worked for you. Yes, you're right - I'll update the README. Thanks again! ;-)

I think info about changing app attributes would also be useful to describe)

**Comment by Ramlevy** [comment]
> `xattr -cr /Applications/CommandShift.app`
@VasylBaran
Had the exact same problem and this solved it! Thanks a bunch.

**Comment by VasylBaran** [comment]
> > `xattr -cr /Applications/CommandShift.app`
> > @VasylBaran
> > Had the exact same problem and this solved it! Thanks a bunch.

I'm glad it worked for you. I plan to find a better solution (so that people wouldn't be getting this error message at all). 
But I'm not sure when this will happen since I'm from Ukraine and currently it's a warzone here. Can't believe I'm writing this, 4 months in and it's still feels surreal...
