### ISSUE TITLE
Can't access CommandShift menu after I've hidden the icon in menu bar

### ISSUE THREAD

**Issue by dmrkv** [VasylBaran/CommandShift#11]
### Problem
Now it is not possible to access menu of the app after icon was hidden

### Idea of a solution
Run the program menu after Command Shift was run through the spotlight, for example

**Comment by mshannaq** [comment]
Me too

after I hide the icon i cannot access the menu

how to access the menu after I remove the icon? is there any way to return the icon or access the menu

**Comment by serrj-sv** [comment]
`defaults delete vasybaran.tempproj.commandshift.CommandShift tray_icon.hide`

**Comment by VasylBaran** [comment]
@dmrkv @mshannaq @serrj-sv please check the latest release where I made it possible to choose whether you would like to hide tray icon from the menu permanently or until restart: https://github.com/VasylBaran/CommandShift/releases/tag/1.03

**Comment by VasylBaran** [comment]
<img width="375" alt="Screenshot 2024-04-28 at 22 39 48" src="https://github.com/VasylBaran/CommandShift/assets/12252940/f9daa390-629b-4923-b50d-c4c451178aeb">
