### ISSUE TITLE
Luanch at startup

### ISSUE THREAD

**Issue by thewh1teagle** [VasylBaran/CommandShift#13]
Can you add the ability to auto launch CommandShift after each reboot?
Currenly I need to manually start it after each reboot.

**Comment by VasylBaran** [comment]
@thewh1teagle you can add CommandShift to your list of auto-start items by opening System Settings panel -> Users and Groups OR General (depending on what version of macOS you're using) -> Login Items -> [+] -> <select CommandShift app>.

Done! =)
