### ISSUE TITLE
bug: Macbook sometimes starts to slow down because of `CommandShift`

### ISSUE THREAD

**Issue by ruscon** [VasylBaran/CommandShift#15]
I have noticed several times that my Macbook sometimes starts to slow down.
And if I turn off “CommandShift”, the speed is restored.

Unfortunately, I don't have any evidence at the moment.

**Comment by VasylBaran** [comment]
@ruscon hmm, that's strange.

By "turn it off" you mean "Force Quit" from "Activity Monitor"? 

Would be nice to check it's CPU/RAM usage during that "slow down" phase to determine if it's CommandShift to blame =)

**Comment by ruscon** [comment]
@VasylBaran no, just quit without force

**Comment by VasylBaran** [comment]
> @VasylBaran no, just quit without force (from menu)
> 
> > Would be nice to check it's CPU/RAM usage during that "slow down" phase to determine if it's CommandShift to blame =)
> 
> I understand, but it's hard to open anything when the MacBook hardly responds to your actions

wow, it's that bad? Are you using M1/2/3 (Arm-based Mac) or an Intel-based one? Also how much RAM do you have?

If you face this issue again, please check RAM/CPU usage of CommandShift (from Activity Monitor) before pressing 'Quit' and post it here. It would be really helpful

<img width="657" alt="Screenshot 2024-03-28 at 14 42 37" src="https://github.com/VasylBaran/CommandShift/assets/12252940/c4cf00da-17d4-443e-b171-2c65414ffa5f">

<img width="661" alt="Screenshot 2024-03-28 at 14 42 18" src="https://github.com/VasylBaran/CommandShift/assets/12252940/4587a000-0a53-40dc-a2d5-c40d81552cfb">

**Comment by ruscon** [comment]
Intel 2019y
64 gb ram, but with docker, etc(50 gb is busy)

Ok

**Comment by ruscon** [comment]
2 weeks after, again

**Comment by VasylBaran** [comment]
@ruscon please check the latest release, this issue should be fixed now. It would be great if you can confirm this.   https://github.com/VasylBaran/CommandShift/releases/tag/1.03
