### ISSUE TITLE
Add "Shift ONLY" to the shortcut list

### ISSUE THREAD

**Issue by neolixiang** [VasylBaran/CommandShift#16]
Is it possible to switch between input language by only pressing "Shift"?
Like when you press shift and release it without pressing other keys, it changes the input method;
If you press shift + other keys, use the system default behavior.
Hopefully I made my point clear :)

**Comment by VasylBaran** [comment]
@neolixiang please check the latest release where I implemented this feature: https://github.com/VasylBaran/CommandShift/releases/tag/1.03

**Comment by VasylBaran** [comment]
<img width="410" alt="Screenshot 2024-04-28 at 22 40 24" src="https://github.com/VasylBaran/CommandShift/assets/12252940/ade2e566-282b-4087-a019-781ef745527e">

**Comment by neolixiang** [comment]
thank you for the update!

**Comment by Old-Farmer** [comment]
I have a touble with only use shift. When I press shift a, input method switch also takes effect.

**Comment by VasylBaran** [comment]
> I have a touble with only use shift. When I press shift a, input method switch also takes effect. Do I miss sth ?

Hm.. do you mean that you press two keys (Shift + A) and it switches input method but you don't want that. Right?

**Comment by Old-Farmer** [comment]
> > I have a touble with only use shift. When I press shift a, input method switch also takes effect. Do I miss sth ?
> 
> Hm.. do you mean that you press two keys (Shift + A) and it switches input method but you don't want that. Right?

yes
