### ISSUE TITLE
Solve Conflicts - Trigger Command+Shift AFTER Shift is released, rather than when pressed down. Lucky #17

### ISSUE THREAD

**Issue by fire17** [VasylBaran/CommandShift#17]
### Trigger Command+Shift AFTER Shift is released, rather than when pressed down.

Hi there :)
First of all let me again say that I love Command+Shift 🚀 ❤️ 
but sadly it conflicts and gives me issues any time i use another command that uses both keys. For example: 
`Command+Shift+T` to open recently closed tab, or
`Command+Shift+F` to search in all files
...and so on....

The obvious solution is to only trigger it once Shift is released, **+ No Other Keys Were Pressed**
Pressing another key when Command+Shift is held -
should immedeately Cancel CommandShift's operation

I was looking for if anyone else asked about this and found:

>  A possible solution is that CommandShift could opt-in to trigger input method switch right after Command+Shift is released, rather than pressed down.
_Originally posted by @AlseinX in https://github.com/VasylBaran/CommandShift/issues/3#issuecomment-1221556306_
            
They asked it for a different reason but all the same it will solve all the issues
please please please when you do fix this, make sure to include the intel version!
(or else i wont be able to enjoy it 😭 )

_while you're at it, it would be nice if in the next release you would check if it is Intel based or not, and if so, load the logic from the 1.0.1
It's funny that we have to get a specific version, the most recent one should figure it out and be compatible with both cases_

Thanks a lot and All the best!

**Comment by VasylBaran** [comment]
@fire17 please check the latest release where I tacked this: https://github.com/VasylBaran/CommandShift/releases/tag/1.03

**Comment by VasylBaran** [comment]
<img width="278" alt="Screenshot 2024-04-28 at 22 41 02" src="https://github.com/VasylBaran/CommandShift/assets/12252940/3fdfb0d2-e6c0-43fc-be1d-86e50aac1ebf">

**Comment by fire17** [comment]
That's awesome! Right on time!
Will it work with Intels aswell?

All the best!

**Comment by VasylBaran** [comment]
> That's awesome! Right on time! Will it work with Intels aswell?
> 
> All the best!

Yes, if works for both Intel and Arm based Macs 🙂

**Comment by The-city-not-present** [comment]
Absolutely great, thank you.
1. I believe it should be checked by default. When you press Cmd+Shift+Left (select all typed text to the beginning) or Cmd+Shift+N (new folder, or new incognito window), the language should not be changed.
2. This "issue" is still Open, won't you move it to Resolved or Closed since it's done?
