### ISSUE TITLE
Can't run the app - Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by obetav** [VasylBaran/CommandShift#18]
Hi,

I am getting this message:
“CommandShift” can’t be opened because Apple cannot check it for malicious software.
This software needs to be updated. Contact the developer for more information.
How do I solve this?
Thanks!

**Comment by VasylBaran** [comment]
hi @obetav ! Which version of macOS are you using?

**Comment by obetav** [comment]
MacOS Sonoma 14.5

**Comment by VasylBaran** [comment]
@obetav here, I've rebuilt CommandShift on Sonoma (14.4.1). 
Give it a try and let me know if you still see that error.

[CommandShift-universal.dmg.zip](https://github.com/user-attachments/files/16029317/CommandShift-universal.dmg.zip)

**Comment by VasylBaran** [comment]
@obetav did it work?

**Comment by obetav** [comment]
HI @VasylBaran No, I just tried and it still shows this message

**Comment by VasylBaran** [comment]
@obetav and if you run `xattr -cr /Applications/CommandShift.app` from terminal?

**Comment by VasylBaran** [comment]
Assuming CommandShift.app is already in /Applications folder

**Comment by obetav** [comment]
Yes! I did xattr -cr and then I had to open the CommandShift app from the application folder. Now I see it works!
Thank you so much!

**Comment by obetav** [comment]
Do I need to run the app every time I restart my mac?

**Comment by obetav** [comment]
Also, can't donate via paypal "due to regulation".

**Comment by VasylBaran** [comment]
> Yes! I did xattr -cr and then I had to open the CommandShift app from the application folder. Now I see it works! Thank you so much!

I'm happy to hear that it worked! In general such issues are the result of the fact that I don't have an Apple Developer account to properly sign my application because it costs $100 per year and I'm not yet in the position to pay that kind of money to Apple. Google account costs $35 for life-time which is more reasonable fee.

**Comment by VasylBaran** [comment]
> Also, can't donate via paypal "due to regulation".

oops... that's odd. I'll check what's going on, thank you for pointing that out! ;-)

**Comment by VasylBaran** [comment]
@obetav I've updated PayPal donation link. Don't feel you have to donate anything, please take care of yourself first. However I would really appreciate if you could tell if the new link works properly now because I didn't even realize there was an issue until you pointed that out. 🙂

[https://www.paypal.com/donate/?hosted_button_id=WZAJV3PYPWUHA](https://www.paypal.com/donate/?business=D44S767JVTAP8&no_recurring=0&item_name=Thank+you+for+your+support%2C+it+is+much+appreciated%21&currency_code=USD)

**Comment by obetav** [comment]
Yes. I made a donation.
Take care
Oded

From: Vasyl_Baran ***@***.***>
Date: Sunday, 30 June 2024 at 11:19
To: VasylBaran/CommandShift ***@***.***>
Cc: Oded Betav ***@***.***>, Mention ***@***.***>
Subject: Re: [VasylBaran/CommandShift] Can't run the app - Apple cannot check it for malicious software (Issue #18)
CAUTION: This email originated from outside of Chegg. Do not click links or open attachments unless you recognize the sender and know the content is safe.


@obetav<https://urldefense.com/v3/__https:/github.com/obetav__;!!OH6fMn4!AwXP6raVPFri0tHKpEI7lPD5j9vEzQpCiMq4OJoo5_BREBURALE0mDP8T-P8DNo8r2wh9wqspfk2XKnomnER_g$> I've updated PayPal donation link. Don't feel you have to donate anything, please take care of yourself first. However I would really appreciate if you could tell if the new link works properly now because I didn't even realize there was an issue until you pointed that out. 🙂

https://www.paypal.com/donate/?hosted_button_id=WZAJV3PYPWUHA<https://urldefense.com/v3/__https:/www.paypal.com/donate/?business=D44S767JVTAP8&no_recurring=0&item_name=Thank*you*for*your*support*2C*it*is*much*appreciated*21&currency_code=USD__;KysrKyUrKysrJQ!!OH6fMn4!AwXP6raVPFri0tHKpEI7lPD5j9vEzQpCiMq4OJoo5_BREBURALE0mDP8T-P8DNo8r2wh9wqspfk2XKlRH1LQ-Q$>

**Comment by VasylBaran** [comment]
@obetav thank you very much! I really appreciate it ❤️

**Comment by VasylBaran** [comment]
> Do I need to run the app every time I restart my mac?

You can add CommandShift to your list of auto-start items by going to System Settings panel -> General -> Login Items -> [+] -> [select CommandShift app]

P.S. thanks again for your donation! It seems that [PayPal has limited transactions from non-family members](https://www.paypal-community.com/t5/Transactions-Archives/Payments-to-Paypal-through-Donate-button-to-Ukraine-do-not-work/td-p/2910186) to the country where I live (Ukraine) so I couldn't really "Accept" your donation on PayPal, I could only "Deny" it which I did. Your donation should get back to you shorty. 

I'll use a different donation-service going forward (https://buymeacoffee.com/vasylbaran seems like a good alternative and it works in Ukraine). Sorry for this mess with donations, you're the first person who tried to donate 😉
