### ISSUE TITLE
Implement GitHub releases

### ISSUE THREAD

**Issue by unickq** [VasylBaran/CommandShift#2]
Not cool to open bitbucket or sourceforge everytime :) 

If GitHub is your main repo it'd be great to implement releases and versioning here

**Comment by VasylBaran** [comment]
I'll consider it. Thanks

**Comment by VasylBaran** [comment]
There you go =)

https://github.com/VasylBaran/CommandShift/tree/main/Releases

**Comment by unickq** [comment]
I meant https://github.com/VasylBaran/CommandShift/releases, not adding dmg to git ;)

**Comment by VasylBaran** [comment]
> I meant https://github.com/VasylBaran/CommandShift/releases, not adding dmg to git ;)

Opps, fixed it. It's first I'm publishing on GitHub. Thanks for your help!
