### ISSUE TITLE
Unable to switch to third keyboard layout

### ISSUE THREAD

**Issue by PetrovskYYY** [VasylBaran/CommandShift#4]
The program works excellently while switching between two last keyboard layouts, but due to my country specifics (Ukraine), I need to use three layouts (English, Russian and Ukrainian). 
Chosen key combination switches only between the last two of the three layouts if I need to switch to the third layout I still need to use CTRL+SPACE or choose from the layout menu using the mouse.

I think that situation will be the same with 4 or more layouts.

MacOS 12.6.1 MacBook Pro (Retina, 13-inch, Early 2015)

**Comment by VasylBaran** [comment]
@PetrovskYYY thank you posting, I will look into it 😉

Stay safe! )

**Comment by VasylBaran** [comment]
@PetrovskYYY hi again! Unfortunatelly [it seems](https://support.apple.com/guide/mac-help/write-in-another-language-on-mac-mchlp1406/mac) that the default macOS behavior for switching input sources is to just switch between the 2 most recent ones. So if you use more than 2 input sources you will end up just cycling between the 2 out of 3 input sources (even when using Apple's default shortcuts)

One possible workaround is to press Shift key one more time while holding Command key (or whichever key you've set in CommandShift app). 

Check my video below, I know it's not exactly what you've asked for but... I hope it'll help )

https://user-images.githubusercontent.com/12252940/200273553-dab44204-75fb-4c35-ab27-272a82acd840.mov

**Comment by PetrovskYYY** [comment]
I can use the default MacOS keys to switch between all three layouts. 
I could not change to the third layout using the workaround you proposed.
Please, look at the video below: 

https://user-images.githubusercontent.com/4482272/202471264-557c9568-9e58-4426-a2c8-29a0edfa28e1.mp4

First I had been changing the layout with Alt/Option+Shift (changing to the third layout did NOT work)
Then I changed the layout using standard Ctrl+Space (changing to the third layout works)
Then tried to hit the second shift button and to press shift several times (changing to the third layout did NOT work)

**Comment by PetrovskYYY** [comment]
@VasylBaran, please look at the previous post.

**Comment by PetrovskYYY** [comment]
Finally got the desired behaviour by changing the default key combination from switching to the PREVIOUS key combination to the NEXT key combination. Now I am able to use all input sources I have: 
![image](https://user-images.githubusercontent.com/4482272/225306093-0a021875-d1d1-4044-8ffb-67070817ed54.png)
I hope this will help someone.

**Comment by sepazik** [comment]
> Finally got the desired behaviour by changing the default key combination from switching to the PREVIOUS key combination to the NEXT key combination. Now I am able to use all input sources I have: ![image](https://user-images.githubusercontent.com/4482272/225306093-0a021875-d1d1-4044-8ffb-67070817ed54.png) I hope this will help someone.

Perfect. It's work for me!! Love u
