### ISSUE TITLE
Does not work when default input source shortcuts are disabled

### ISSUE THREAD

**Issue by adekusar-drl** [VasylBaran/CommandShift#5]
First off, thanks for the great app. The problem I'm facing is that I have disabled default shortcuts for changing input sources. I know, you mentioned they must be enabled. But... One of the defaults, Ctrl+Space is also a code completion shortcut that I will never change to anything else, that's why it is disabled as a shortcut to change input source. I guess, you understand why Ctrl+Space is so unique. Any chances the app can deal with this problem?  And stay safe!

**Comment by Yrfo** [comment]
same here. I would like to use default Ctrl+Space for code completions. 
For that I guess would be nice to have an option to work with other key combinations. E.g. I set in system settings control+L and then I tell somehow it to CommandShift that it can map desired key combination to the combination I want for language change.

**Comment by kpripper** [comment]
Підтверджую, якщо вимкнути - мова не переключається. Зробив там довільний шорткат і все працює. Дякую!
