### ISSUE TITLE
Doesn't seem to work on Ventura 13.0.1 

### ISSUE THREAD

**Issue by mfractal** [VasylBaran/CommandShift#7]
I've enabled CS in accessibility (although the path now is different from the instructions and it's Privacy & Security -> Accessibility)

<img width="707" alt="Screenshot 2023-02-01 at 11 38 34" src="https://user-images.githubusercontent.com/1019437/216072928-baf24715-0dff-42ad-bd6a-1f8df684b672.png">

but using the key combination that is selected in CS options doesn't trigger a language change

**Comment by Sergei-Timoshenko** [comment]
Same problem.

**Comment by VasylBaran** [comment]
@mfractal @sergei-timoshenko please check the latest release, I've tested it on Ventura 13.6.6: https://github.com/VasylBaran/CommandShift/releases/tag/1.03
