### ISSUE TITLE
Hide menu icon

### ISSUE THREAD

**Issue by jackyfox** [VasylBaran/CommandShift#9]
Hello,

Thank you for the app. Really useful.

Is there any way to hide menu icon of this app?

**Comment by VasylBaran** [comment]
Hello @jackyfox! You're very welcome, I'm glad you find it useful. 

I believe you can remove any icon from menu bar by holding down the Command (⌘) key, left click and drag the icon you want to remove out of the menu bar and onto the desktop - and let it go... Let it go! 🙂

**Comment by jackyfox** [comment]
> holding down the Command (⌘) key, left click and drag the icon

It works with default system icons like Volume, Battery and WiFi, but I can't remove CommandShift icon :(

https://user-images.githubusercontent.com/693161/235354173-a806bbf2-ff30-4bfb-83f0-173fb75e1266.mov

**Comment by lucellent** [comment]
Any solutions yet? I have the same issue.

**Comment by VasylBaran** [comment]
Hi @jackyfox and @lucellent! I'm grad you find my app useful. 
In [release 1.02](https://github.com/VasylBaran/CommandShift/releases/tag/1.02) I made it possible to hide app-icon from system's tray menu

Just press the button once and that's it. Cheers from Ukraine! ;-)
<img width="214" alt="Screenshot 2023-08-12 at 17 21 16" src="https://github.com/VasylBaran/CommandShift/assets/12252940/1b2d90e1-4ed4-4d60-9b31-aa6e236f745c">

**Comment by lucellent** [comment]
Awesome! Thanks a lot

**Comment by dmrkv** [comment]
How to access app's menu after I removed the icon?

**Comment by mshannaq** [comment]
> Any solutions yet? I have the same issue.

same here. how to access the app menu after I remove the icon?

**Comment by serrj-sv** [comment]
@dmrkv @mshannaq 
`defaults delete vasybaran.tempproj.commandshift.CommandShift tray_icon.hide`

**Comment by serrj-sv** [comment]
> How to access app's menu after I removed the icon?

`defaults write vasybaran.tempproj.commandshift.CommandShift tray_icon.hide 0`

**Comment by VasylBaran** [comment]
@jackyfox @lucellent @dmrkv @mshannaq @serrj-sv please check the latest release where I made it possible to choose whether you would like to hide tray icon from the menu permanently or until restart: https://github.com/VasylBaran/CommandShift/releases/tag/1.03

**Comment by VasylBaran** [comment]
<img width="375" alt="Screenshot 2024-04-28 at 22 39 48" src="https://github.com/VasylBaran/CommandShift/assets/12252940/f9daa390-629b-4923-b50d-c4c451178aeb">
